### ISSUE TITLE
Can't run example - missing flutter_angle package

### ISSUE THREAD

**Issue by obiwanzenobi** [Knightro63/three_js#1]
Hello,

Your package looks like a game changer for flutter!
I was trying to run example but I stuck on pub get - I throws out:

```
Because every version of three_js from path depends on three_js_math from path which depends on flutter_angle from path, every version of three_js from path requires flutter_angle from path.
So, because flutter_angle from path doesn't exist (could not find package flutter_angle at "../../../../flutter_angle") and example depends on three_js from path, version solving failed.
```

Where should I look to find flutter_angle package?

**Comment by Knightro63** [comment]
Hi @obiwanzenobi,

Sorry for the issue. You have one of three options.

1) download https://github.com/Knightro63/flutter_angle and place it in the same location you unzipped three_js.
2) Change the yaml in three_js/packages/three_js_math to 
```yaml
  flutter_angle:
    git:
      url: https://github.com/Knightro63/flutter_angle.git
```
3) I will probably publish this on pub by next Friday.

Hope this helps.
