### ISSUE TITLE
How To Set Background to alpha

### ISSUE THREAD

**Issue by RansomBroker** [Knightro63/three_js#11]
Hi, sorry for asking, i'm new to flutter, on three js web i can set alpha background by set render alpha true, how i can achieve that ? because i want stacking a widget, behind it

thanks in advance

![image](https://github.com/user-attachments/assets/12a97fcb-f229-43f8-becb-bb72a0f76c8d)

![image](https://github.com/user-attachments/assets/351810eb-e66d-42bd-8ba8-f93e3aeab540)

i have modified multiview but the container line not show, event i was set alpha to true

**Comment by Knightro63** [comment]
Hi @RansomBroker,

To get the alpha to work you will need to add the settings for the ThreeJS class.

'''dart
threeJs = three.ThreeJS(
  onSetupComplete: (){setState((){});},
  setup: setup,
  settings: three.Settings(
    alpha: true,
    clearAlpha: 0.0,
    clearColor: 0x000000
  )
);
'''

There is an issue in ThreeJS.build you will need to go in and change the color parameters to Colors.tranparent.

Hope this helps

**Comment by Knightro63** [comment]
This should now be fixed in the latest release.
