### ISSUE TITLE
Error running on android

### ISSUE THREAD

**Issue by worldwidee** [Knightro63/three_js#12]
Hello, I was trying to run three_js but got this error

```
three_js: ^0.0.6
```

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_angle'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 974ms
Error: Gradle task assembleDebug failed with exit code 1
```

**Comment by Knightro63** [comment]
Hi @worldwidee,

I am sorry for the issue. I believe this only occurs with the new upgraded version of flutter. They have moved to kotlin version >8.x.x. 

For a temp fix please go to you settings.gradle file and change the plugins section to the code below. 

```gradle
plugins {
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.3.0" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
}
```

I will work on upgrading the android manifest soon.

Thanks you for letting me know of the issue.

**Comment by Knightro63** [comment]
Hi @worldwidee,

This issue should now be resolved with the newest version of flutter_angle.

**Comment by AliGanjehei** [comment]
same error but for simple_sensor
A problem occurred configuring project ':simple_sensor'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

**Comment by Knightro63** [comment]
Hi @AliGanjehei,

It looks like simple_sensors needs to be updated. I will see if I can do a pull request or make a version specifically for three_js.

Hope to have this solved soon

**Comment by AlexanderMonneret** [comment]
same problem with the simple_sensors :*(
btw thanks a lot for the amazing plugin

**Comment by AlexanderMonneret** [comment]
That was very quick, really appreciate it!

**Comment by urbste** [comment]
I wanted to experiment with three_js in flutter as well, however I run into the same error with simple_sensors. 
I am not an experienced flutter developer and have no clue how to fix this issue with the gradle build settings. 
Where can I find the simple_sensors-0.1.7 pub cache? :)

**Comment by Knightro63** [comment]
Hi @urbste,

Depends on your operating system. For mac the files are hidden you will need to go to /Users/%USERNAME%/ and press (CMD+SHIFT+.) to show hidden files. Then you can go to /.pub-cache/hosted/pub.dev/simple_sensor-0.1.7. Or open finder window press (CMD+SHIFT+G) and type in /Users/%USERNAME%/.pub-cache/hosted/pub.dev/simple_sensor-0.1.7 . For Windows C:\Users\<user_name>\AppData\Roaming\Pub\Cache.

Hope this helps

**Comment by Mamena2020** [comment]
Any update of this issues?

**Comment by urbste** [comment]
@Knightro63 Thanks! That actually worked. Still it would be great if the simple_sensor package could be updated. :)
