### ISSUE TITLE
orbit_controls There is a bug

### ISSUE THREAD

**Issue by leesser** [Knightro63/three_js#15]
When using OrthographicCamera and maxPolarAngle is 0, it cannot be rotated after moving.

**Comment by Knightro63** [comment]
Hi @leesser,

I tried to replicate your issue on mac, ios, and web, but was not able to not get the desired result. Could you please provide what platform you are using.

Also please check out [this](https://github.com/Knightro63/three_js/blob/main/examples/lib/controls/misc_controls_orbit.dart) example I have updated to see if this has the same issue.

Sorry for the inconvenience.
