### ISSUE TITLE
Light With castShadow enabled, models in the scene are no longer visible

### ISSUE THREAD

**Issue by vincentChen02** [Knightro63/three_js#18]
Hi,
I tried to add a cast, but it didn't work.

The version used is Android Studio Giraffe | 2022.3.1 Patch 3.
Running on a Huawei HONOR 9X real machine.

The code is as follows:
`
  Future<void> setup() async {
    threeJs.camera =
        three.PerspectiveCamera(30, threeJs.width / threeJs.height, 1, 2200);
    threeJs.camera.position.setValues(cameraPos.x, cameraPos.y, cameraPos.z);
    threeJs.scene = three.Scene();
    threeJs.camera.lookAt(threeJs.scene.position);
    threeJs.scene.add(threeJs.camera);

    final light = three.DirectionalLight(0xffffff, 1);
    light.position.setValues(5, 10, 7);
    // light.castShadow = true; // You can't see it if you open it here
    threeJs.scene.add(light);

    three.PlaneGeometry planeGeometry = three.PlaneGeometry(100, 100);
    three.MeshBasicMaterial planeMaterial =
        three.MeshBasicMaterial({three.MaterialProperty.color: 0xaaaaaa});
    three.Mesh plane = three.Mesh(planeGeometry, planeMaterial);
    plane.receiveShadow = true;
    threeJs.scene.add(plane);

    three.MeshStandardMaterial material =
        three.MeshStandardMaterial({three.MaterialProperty.color: 0x00ff00});
    three.Mesh model = three.Mesh(three.BoxGeometry(1, 1, 1), material);
    model.castShadow = true;
    model.position.y = 1;
    threeJs.scene.add(model);

    // threeJs.renderer!.autoClear = false;
    threeJs.renderer!.shadowMap.enabled = true;
    threeJs.postProcessor = ([double? dt]) {
      threeJs.renderer!.setViewport(0, 0, threeJs.width, threeJs.height);
      threeJs.renderer!.clear();
      threeJs.renderer!.render(threeJs.scene, threeJs.camera);
      threeJs.renderer!.clearDepth();
    };
  }
`
1. When not turned on, the plane and model display normally.
![Snipaste111](https://github.com/user-attachments/assets/bd93f928-dbfb-4c38-8a60-4ff68a64546e)

2. Turn on the castShadow of the light, neither the plane  nor the model  is displayed
![Snipaste222](https://github.com/user-attachments/assets/9a14d8b6-55d8-4bd6-9449-c9ba1a775028)

**Comment by Knightro63** [comment]
Hi @vincentChen02,

Sorry to hear you are having an issue.

Please remove the post processor from threeJs and initialize it to be

```dart
   threeJs = three.ThreeJS(
      onSetupComplete: (){setState(() {});},
      setup: setup,
      settings: three.Settings(
        useSourceTexture: true
      )
    );
```

Hope this helps.

**Comment by vincentChen02** [comment]
Thank you very much for your reply @Knightro63 . 
Your answer solves the problem perfectly.
Have a good day!

**Comment by vincentChen02** [comment]
Hi!@Knightro63
I'm sorry to bother you again.
Q1:Why do I need to turn on useSourceTexture to see the light set shadows?
Q2:At present, after useSourceTexture is enabled in the Settings, the shadow can be displayed normally, but the model lighting is slightly different, showing a dark red situation, and adjusting attributes such as roughness has no effect.

If useSourceTexture is not set, the following information is displayed:
![Snipaste_not_1](https://github.com/user-attachments/assets/8d3d809e-caa9-4d2b-9d57-f0ef45dc4a9c)
![Snipaste_not_2](https://github.com/user-attachments/assets/2f5f84b6-a4be-476c-b03b-e9a6f2d584e1)

If useSourceTexture is set to true, the following is displayed:
![Snipaste_1](https://github.com/user-attachments/assets/92abeece-818f-4a8e-be0b-43fac4eeff82)
![Snipaste_2](https://github.com/user-attachments/assets/9d5d5f38-d723-4755-9f58-aad5dc99794b)

Try to modify the light intensity and position, the roughness, metalness, emissive and other properties of the material, can not be adjusted to the same as when not opened, especially the face is dark red.

thank you!

**Comment by Knightro63** [comment]
Hi @vincentChen02,

I am sorry you are having an issue with this. The useSourceTexture adds the shadow layer onto the scene. This is required for every platform except for web. I have tried to fix the issue but was unsuccessful. 

I will look into this further. The creation of the shadow layer might have too high of a red hex value.

I will update you if I solve the issue.

**Comment by vincentChen02** [comment]
Look forward to your follow-up version, thank you very much, wish better and better!
