### ISSUE TITLE
Help! DeviceOrientationController example.

### ISSUE THREAD

**Issue by vivagelive** [Knightro63/three_js#2]
Good afternoon, thank you very much for the project. Is there any example with DeviceOrientationController so that I can use it? I tried to use it, but nothing works. Thank you.

**Comment by Knightro63** [comment]
Hi @vivagelive,

There is currently no example. I will take a look and see why it is not working and also place the example for it in examples. Just be aware that this type of controls only works on iOS and android. 

I hope everything else is working as planned for you.

**Comment by vivagelive** [comment]
Yes, I understand that controller just for ios and Android. It seems to me that the **_Peripherals class_** is not listening to events and not receiving data because there is no event handling. I’m newbee but I`m trying to do this, but I don’t understand which event to expect. 
![Screenshot_1](https://github.com/user-attachments/assets/7d581630-425a-4304-8d71-8285cd008b63)

**Comment by Knightro63** [comment]
Hi @vivagelive,

Yes you are correct it is missing. I am adding sensors_plus: ^5.0.1 to three_js_controls yaml. I will use the accel and gyro data to rotate the camera accordingly. 

This will take me a little while to implement and publish.

**Comment by vivagelive** [comment]
Very glad to hear this. I will wait with anticipation. Thank you once again. I will do my best to help you with the project to the best of my abilities as a beginner, because I really like it. :)

**Comment by Knightro63** [comment]
Hi @vivagelive,

I have updated the package try the new three_js: ^0.0.3 in your yaml file to see if that fixes the issue. It says it only works for ios and android but this is false and I will fix that issue later. Also there is a new example of this in the examples folder.

Hope this helps.

**Comment by vivagelive** [comment]
Hi @Knightro63 . 
It works perfectly, thank you! 

For those who want to try, there is a small issue with motion_sensors. You need to manually change some fields in the motion_sensors package. As described here: [motion_sensors/pull/17](https://github.com/zesage/motion_sensors). Maybe it will help someone. Thanks again, @Knightro63 

https://github.com/user-attachments/assets/d76fd314-3309-4199-913e-0d187858f319
