### ISSUE TITLE
Migration three_dart/three_js

### ISSUE THREAD

**Issue by MapleNoise** [Knightro63/three_js#3]
Hi,
I will try to migrate my three_dart project on this three_js lib, I will keep you informed.

If you want take a look my lib cannon-es for collision in dart, you can check here : [collision-es.zip](https://github.com/user-attachments/files/16232650/collision-es.zip)
It miss some shapes like Cylinder or Heightfield. But it works like a charm, may be add in your project ?

I attach a video demo of my flutter project for show you the possibilities

https://github.com/user-attachments/assets/c6f70d3d-e0d0-4e3c-a175-6148c018dfa7

**Comment by Knightro63** [comment]
Hi @MapleNoise,

Thanks for taking a look and trying to move your project over. I took a look at your video and your project looks like it is a lot of fun.

It also looks like we had the same thoughts on physics. I also converted cannon physics over about a year ago [here](https://github.com/Knightro63/cannon_physics). Which can be added through pub.dev through the yaml file. 

Please let me know if you have any issues.
