### ISSUE TITLE
Can't run example in Windows

### ISSUE THREAD

**Issue by ZhongGuanbin** [Knightro63/three_js#4]
Thank you very much for your efforts, which enabled us to render 3D models on Flutter. 
When I ran the example on the web platform, everything went smoothly. But when I tried to run the example on the Windows platform, the following error message appeared. I have tried updating the OpenGL driver, modifying the CMake file, and adding flutter_angle windows_plugin, but still cannot solve the problem, so I suspect that this may be an internal issue with the plugin. May friends from the community assist in resolving this issue and ensure the demo operates in a Windows environment? Thank you very much!

![image](https://github.com/user-attachments/assets/969b73a7-d47e-414c-97f9-43582ec5f98f)

**Comment by Knightro63** [comment]
Hi @ZhongGuanbin,

Are you running the examples folder or three_js/example? 
What type of windows computer do you have?

I will take a look at it to see what the issue is. 

Sorry for the inconvenience.

**Comment by ZhongGuanbin** [comment]
> Hi @ZhongGuanbin,
> 
> Are you running the examples folder or three_js/example? What type of windows computer do you have?
> 
> I will take a look at it to see what the issue is.
> 
> Sorry for the inconvenience.

Hi @Knightro63 
Thank you for your reply！

I am running the example under your project, which is Three_js/example.

I ran the example in both Windows 11 and Windows 10 environments, and the error that occurred was the same. My computer type is Lenovo's ThinkBook14+ and a desktop computer equipped with Intel i7-13700. My operating environment is shown in the following figure.

Thank you again for your reply, your project, and your contribution to the community!

![image](https://github.com/user-attachments/assets/2a47b6a7-8ab5-47e0-b3c1-6360ccd92593)

**Comment by Knightro63** [comment]
Hi @ZhongGuanbin,

It will take me a couple of days before I can get to my windows computers. I will let you know what I find. 

Thanks for all the info this will be useful for debugging

**Comment by ZhongGuanbin** [comment]
> Hi @ZhongGuanbin,
> 
> It will take me a couple of days before I can get to my windows computers. I will let you know what I find.
> 
> Thanks for all the info this will be useful for debugging

Thanks for your reply very much! I am looking forward to your reply and what the error you have found. My abilities are really limited, and I have not yet identified the problem. Looking forward to your help and expressing my gratitude once again.

**Comment by Knightro63** [comment]
Hi @ZhongGuanbin,

I have updated the flutter_angle package that was causing the issue. Please run `flutter pub upgrade` and make sure flutter_angle is 0.0.3 and the issue should be fixed.

Hope this helps.

**Comment by ZhongGuanbin** [comment]
> Hi @ZhongGuanbin,
> 
> I have updated the flutter_angle package that was causing the issue. Please run `flutter pub upgrade` and make sure flutter_angle is 0.0.3 and the issue should be fixed.
> 
> Hope this helps.

Hi @Knightro63 
Thanks for your reply very much! I have run the example and it has run successfully! Thanks for your help and your contribution to the community and expressing my gratitude once again!
![image](https://github.com/user-attachments/assets/05b3dde6-6486-4cee-b527-4688d0cc7719)
![image](https://github.com/user-attachments/assets/7a47be35-95af-475d-b1c7-11b70402d75b)
![image](https://github.com/user-attachments/assets/82e440a7-9b7c-4d2b-800a-ee32b33440c4)
