### ISSUE TITLE
Unable to run on Ios devices

### ISSUE THREAD

**Issue by nirmal-kc** [Knightro63/three_js#5]
Hi,

First of all, thanks for creating this package which address most of the issues from three_dart. I am facing an issue when trying to run this on my Iphone(Physical Device - 14 Pro Max). Just importing three_js throws the error seen below.

> Launching lib/main.dart on Apple 14ProMax in debug mode...
../../.pub-cache/hosted/pub.dev/three_js_core_loaders-0.0.3/lib/ImageLoader/image_loader_app.dart:87:40: Error: Member not found: 'uint8'.
  image = image?.convert(format:Format.uint8,numChannels: 4);
                                       ^^^^^
>../../.pub-cache/hosted/pub.dev/three_js_core_loaders-0.0.3/lib/ImageLoader/image_loader_app.dart:87:18: Error: The method 'convert' isn't defined for the class 'Image'.
'Image' is from 'package:image/src/image.dart' ('../../.pub-cache/hosted/pub.dev/image-3.3.0/lib/src/image.dart').
Try correcting the name to the name of an existing method, or defining a method named 'convert'.
  image = image?.convert(format:Format.uint8,numChannels: 4);
                 ^^^^^^^

But it works fine on web.

**Comment by nirmal-kc** [comment]
I have just one dependency

**Comment by Knightro63** [comment]
Hi @nirmal-kc,

Looks like the image library is way out of date for you. Could you delete your pubspec.lock file run `flutter clean`, `flutter pub upgrade`. Then make sure image is pub file is > 4.0.0. 

If those two things do not work. Try deleting your podfile.lock file and upgrading pods `arch -86_64 pod install --repo-update`. 

Hope this helps.

**Comment by nirmal-kc** [comment]
@Knightro63,

Thanks a ton. Yes, I was on a very old version of image, because of which I saw the above issue.

**Comment by Knightro63** [comment]
Hi @nirmal-kc,

Looks like dart had an issue bringing the value in as a double. I will update it when I get a chance. Sorry for the inconvenience.

Hope everything else is working well for you though.

**Comment by nirmal-kc** [comment]
@Knightro63,

And, I also updated the aspect ratio to 1.0 from 1. Everything else seems to work. I will be testing gltf loader this week, and will update you if I do see any issues.

**Comment by Knightro63** [comment]
Hi @nirmal-kc,

I have updated three_js_advanced_loaders to version 0.0.5 to fix the issues.

please run `flutter pub upgrade` for this to take effect.

Thank you for letting me know of the issue.

**Comment by Knightro63** [comment]
Hi @nirmal-kc ,

I think we should be able to close this issue.

**Comment by nirmal-kc** [comment]
@Knightro63 Thanks, we can go ahead and close the issue
