### ISSUE TITLE
OpenGL Initialization Issue

### ISSUE THREAD

**Issue by Kvsh-03** [Knightro63/three_js#7]
Receiving this error in the angle.dart file:

![image](https://github.com/user-attachments/assets/c8241aa7-f8f3-4b71-b593-ebae7b678ccd)

**Comment by Knightro63** [comment]
Hi @Kvsh-03,

This is currently an issue on the angle API for windows only. 

Hot restart does not work after angle has been initialized.

I will try to fix the issue as soon as I can. 

Sorry for the inconvenience.

**Comment by Knightro63** [comment]
Hi @Kvsh-03,

I have updated flutter_angle to address the issue. 

Pleas run `flutter pub upgrade` and make sure flutter_angle is 0.0.4.

Hope this helps.

**Comment by Kvsh-03** [comment]
That worked perfectly, thank you.
