### ISSUE TITLE
Error when running on IOS simulator

### ISSUE THREAD

**Issue by namhoang3123** [Knightro63/three_js#9]
<img width="938" alt="Screenshot 2024-08-26 at 11 53 03" src="https://github.com/user-attachments/assets/2e5f7360-9152-4998-b52f-8894d7726a1f">

I found on your package three_js_math using flutter_angle : 0.0.2 but this package take this error please help me to fix or help me do something to fix it thank you 
edit: flutter_angle upgrade to 0.0.4 but im try using 0.0.4 but it dont be change :((

**Comment by Knightro63** [comment]
Hi @namhoang3123,

You have to have a real device at this time. The iOS simulator needs a different angle package that is too large for me to host on pub.dev. Hopefully it will be there in the future, but as of right now it is not.

You will be able to run it on you mac, android simulator, android device, windows, web, or iOS device.

Sorry for the inconvenience.

Please let me know if there is something else I can help with.

**Comment by namhoang3123** [comment]
Hi @Knightro63 ,
Thanks for your comment , I still open this case issue to some time people gonna change flutter_angle in the future. So i'm still using your package . When you can resolve this issue , pls comment to this issue and close it ,.

**Comment by Knightro63** [comment]
Hi @namhoang3123,

iOS simulator is now supported. Please run `flutter pub upgrade` and make sure flutter_angle_darwin is 0.0.2 and flutter_angle is 0.0.5.

If this is fixed please close this issue.

Thanks
